#!/bin/bash
sudo yum -y install httpd elinks
sudo touch /var/www/html/index.html
sudo chmod 666 /var/www/html/index.html
sudo echo "<html><head><title>$HOSTNAME</title></head><body>Hello World this is $HOSTNAME</body></html>" > /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html
sudo service httpd start
